dist: xenial
language: python

sudo: false

matrix:
  include:
    # Django 1.8
    - python: 2.7
      env: DJANGO='dj18'
    - python: 3.5
      env: DJANGO='dj18'
    # Django 1.9
    - python: 2.7
      env: DJANGO='dj19'
    - python: 3.5
      env: DJANGO='dj19'
    # Django 1.10
    - python: 2.7
      env: DJANGO='dj110'
    - python: 3.5
      env: DJANGO='dj110'
    # Django 1.11
    - python: 2.7
      env: DJANGO='dj111'
    - python: 3.4
      env: DJANGO='dj111'
    - python: 3.5
      env: DJANGO='dj111'
    - python: 3.6
      env: DJANGO='dj111'
    # Django 2.0
    - python: 3.4
      env: DJANGO='dj20'
    - python: 3.5
      env: DJANGO='dj20'
    - python: 3.6
      env: DJANGO='dj20'
    # Django 2.1
    - python: 3.5
      env: DJANGO='dj21'
    - python: 3.6
      env: DJANGO='dj21'
    - python: 3.7
      env: DJANGO='dj21'
    # Django 2.2
    - python: 3.5
      env: DJANGO='dj22'
    - python: 3.6
      env: DJANGO='dj22'
    - python: 3.7
      env: DJANGO='dj22'

install:
  - pip install tox coveralls
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PY_VER=py27; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then export PY_VER=py34; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PY_VER=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PY_VER=py36; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PY_VER=py37; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOX_ENV=$PY_VER-$DJANGO; fi"

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
