language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="1.7.11"
    - python: "2.6"
      env: DJANGO="1.8.9"
    - python: "2.6"
      env: DJANGO="1.9.2"
    - python: "2.6"
      env: DJANGO="dev"
    - python: "3.3"
      env: DJANGO="1.4.10"
    - python: "3.3"
      env: DJANGO="1.9.2"
    - python: "3.4"
      env: DJANGO="1.4.10"
    - python: "3.5"
      env: DJANGO="1.4.10"
    - python: "3.5"
      env: DJANGO="1.5.5"
    - python: "3.5"
      env: DJANGO="1.6.2"
    - python: "3.5"
      env: DJANGO="1.7.11"
install:
   - "if [[ $DJANGO == 'dev' ]]; then pip install git+https://github.com/django/django.git#egg=Django; else pip install Django==$DJANGO --use-mirrors; fi"
   - pip install -r requirements.txt --use-mirrors
   - python setup.py develop
env:
  - DJANGO="1.4.10"
  - DJANGO="1.5.5"
  - DJANGO="1.6.2"
  - DJANGO="1.7.11"
  - DJANGO="1.8.9"
  - DJANGO="1.9.2"
  - DJANGO="dev"
script: python setup.py test
