language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="1.4.10"
install:
   - "if [[ $DJANGO == 'dev' ]]; then pip install git+https://github.com/django/django.git@stable/1.5.x#egg=Django; else pip install Django==$DJANGO --use-mirrors; fi"
   - pip install -r requirements.txt --use-mirrors
   - python setup.py develop
env:
  - DJANGO="1.4.10"
  - DJANGO="1.5.5"
  - DJANGO="1.6.2"
  - DJANGO="dev"
script: python setup.py test
